import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/disneymovies.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';


export default function MovieList() {
  console.log(record);
  const router = useRouter();

  const [hoveredIndex, setHoveredIndex] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');


  useEffect(() => {
    const fetchImages = async () => {
      const res = await fetch('/disneymovies.json');
      const data = await res.json();
      setImages(data);
    };
    fetchImages();
  }, []);




  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@500&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header1}><h1>Movie List</h1></div>
        
        <div className={styles.wrapper}>

          {
            record.map((rec, index) => {
              return (
                <div key={rec.id} className={styles.container}>


                  <div className={styles.movieTitle}>{rec.Name}</div>


                </div>
              )
            })
          }


        </div>
      </main>
    </>
  )
}