import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/arts.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';
import $ from 'jquery';

function NavigationIcon() {
  const [isOpen, setIsOpen] = useState(false);

  function handleClick() {
    setIsOpen(!isOpen);
  }

  return (
    <div id="nav-icon" className={isOpen ? 'open' : ''} onClick={handleClick}>
      <span></span>
      <span></span>
      <span></span>
    </div>
  );
}

export default function Home(){

  const r = useRouter();

  useEffect(() => {
    $(document).ready(function() {
      $('#nav-icon1,#nav-icon2,#nav-icon3,#nav-icon4').click(function() {
        $(this).toggleClass('open');
      });
    });
  }, []);

  return (
    <>
      <Head>
      <title>ACNH ARTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Blathers.png" />
      </Head>

      <main className={styles.main}>
        <NavigationIcon />
        <div className={styles.header}>
          <h1>Welcome to Museum in Animal Crossing </h1>
        </div>
        <div className={styles.blathers}>
          <img 
            src="Blathers.png"
            width={400}
            height={400}
          />
        </div>
        <button 
          className={styles.Btn}
          onClick={() => r.push("/arts")}
        >
          See Museum Arts
        </button>
      </main>
    </>
  );
}


export default function Home(){

  const r = useRouter();

  return (
    <>
      <Head>
      <title>ACNH ARTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Blathers.png" />
      </Head>

      <main className={styles.main}>
      <div className={styles.header}>
        <h1>Welcome to Museum in Animal Crossing </h1>
        </div>
        <div className={styles.blathers}>
              <img 
                  src="Blathers.png"
                  width={400}
                  height={400}
              /></div>
        <button 
                className={styles.Btn}
                onClick={
                  ()=>r.push("/arts")} >See Museum Arts</button>
      </main>
    </>
  );
}
