import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/arts.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';
import Menu from '../component/menu'

export default function Home(){

  const r = useRouter();

  return (
    <>
      <Head>
      <title>ACNH ARTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Blathers.png" />
      </Head>

      <main className={styles.main1}>
        <Menu></Menu>
      <div className={styles.header}>
        <h1>Welcome to Museum in Animal Crossing </h1>
        </div>
        <div className={styles.blathers}>
          <div className={styles.bubble}>
            <a>Be careful when buying fake arts!</a><br></br>
            <a>It cannot be donated to the Museum or sold in Nook's Canny.</a>
          </div>
              <img 
                  src="Blathers.png"
                  width={400}
                  height={400}
              />
            </div>
            <div className={styles.wrapper}>
    <a class="button" href="#">Hover me!</a>
</div>
<svg style="visibility: hidden; position: absolute;" width="0" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1">
    <defs>
        <filter id="goo"><feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />    
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo" />
            <feComposite in="SourceGraphic" in2="goo" operator="atop"/>
        </filter>
    </defs>
</svg>

      </main>
    </>
  );
}
