import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/arts.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';


export default function Home(){

  const r = useRouter();
// Create a style element
const style = document.createElement('style');
document.head.appendChild(style);

// Define the @font-face rule for your custom font
const fontFace = `@font-face {
  font-family: 'CustomFont';
  src: url('path/to/your/FinkHeavy.ttf') format('truetype');
}`;

// Add the @font-face rule to the style element
style.appendChild(document.createTextNode(fontFace));

// Apply the custom font to an element
const element = document.getElementById('your-element-id');
element.style.fontFamily = 'CustomFont';

  return (
    <>
      <Head>
      <title>ACNH ARTS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Blathers.png" />
      </Head>

      <main className={styles.main} id ="museum">
      <div className={styles.header}>
        <h1>Welcome to Museum in Animal Crossing </h1>
        </div>
        <button 
                className={styles.customBtn}
                onClick={
                  ()=>r.push("/arts")}

              >See Museum Arts</button>
      </main>
    </>
  );
}
